CREATE TABLE measurement (
                             id INTEGER generated by default as identity PRIMARY KEY,
                             name VARCHAR NOT NULL UNIQUE,
                             short_name VARCHAR NOT NULL UNIQUE
);