spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/${NOTIFICATION_DB_NAME}
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASS}

  kafka:
    bootstrap-servers: kafka-broker:9092 # Use 'localhost:9092' for local dev without Docker
    consumer:
      group-id: notification-group # Default group for consumers
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer