server:
  servlet:
    context-path: /api/user-management

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/${USER_DB_NAME:users}
    username: ${USER_DB_USER:user_db_user}
    password: ${USER_DB_PASS:user_pass}

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  cloud:
    openfeign:
      client:
        config:
          integration:
            url: http://integration-service:8080

  kafka:
    bootstrap-servers: kafka-broker:9092 # Use 'localhost:9092' for local dev without Docker
    consumer:
      group-id: notification-group # Default group for consumers
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
        notifications: notification-events

mybatis:
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:config/mybatis.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 120000