#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    -- invoice
    CREATE USER $INVOICE_DB_USER WITH PASSWORD '$INVOICE_DB_PASS';
    CREATE DATABASE $INVOICE_DB_NAME WITH OWNER = $INVOICE_DB_USER;
#    GRANT ALL PRIVILEGES ON DATABASE $INVOICE_DB_NAME TO $INVOICE_DB_USER;

    -- notification
    CREATE USER $NOTIFICATION_DB_USER WITH PASSWORD '$NOTIFICATION_DB_PASS';
    CREATE DATABASE $NOTIFICATION_DB_NAME WITH OWNER = $NOTIFICATION_DB_USER;
#    GRANT ALL PRIVILEGES ON DATABASE $NOTIFICATION_DB_NAME TO $NOTIFICATION_DB_USER;

    -- user
    CREATE USER $USER_DB_USER WITH PASSWORD '$USER_DB_PASS';
    CREATE DATABASE $USER_DB_NAME WITH OWNER = $INVOICE_DB_USER;
#    GRANT ALL PRIVILEGES ON DATABASE $USER_DB_NAME TO $USER_DB_USER;

EOSQL