spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/${INVOICE_DB_NAME}
    username: ${INVOICE_DB_USER}
    password: ${INVOICE_DB_PASS}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api/invoice/v3/api-docs/swagger-config
  api-docs:
    enabled: true
    path: /v3/api-docs