server:
  servlet:
    context-path: /api/invoice

spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/${INVOICE_DB_NAME:postgres}
    username: ${INVOICE_DB_USER:elvin}
    password: ${INVOICE_DB_PASS:15112002}



  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  cloud:
    openfeign:
      client:
        config:
          user-management:
            url: http://user-service

          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: basic

mybatis:
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:config/mybatis.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    liquibase: DEBUG