server:
  servlet:
    context-path: /api/invoice

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5433/${INVOICE_DB_NAME}
    username: ${INVOICE_DB_USER}
    password: ${INVOICE_DB_PASS}

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    liquibase: DEBUG
