server:
  servlet:
    context-path: /api/invoice

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    username: postgres
    password: 12345

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  cloud:
    openfeign:
      client:
        config:
          user-management:
            url: http://user-service:8080

          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: basic

mybatis:
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:config/mybatis.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    liquibase: DEBUG